# KubeRCA does not currently accept monetary funding.
# When sponsorship is enabled, populate the providers below.
# Documentation: https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository
#
# github: KKamJi98
# custom: ['https://example.com/sponsor']
