apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: details-fault-abort
spec:
  hosts:
  - details
  http:
  - fault:
      abort:
        percentage:
          value: 100
        httpStatus: 500
    route:
    - destination:
        host: details
        port:
          number: 9080
