apiVersion: chaos-mesh.org/v1alpha1
kind: StressChaos
metadata:
  name: reviews-oom-stress
  namespace: kube-rca
spec:
  mode: one
  selector:
    labelSelectors:
      app: chaos-oom-target
  stressors:
    memory:
      workers: 1
      size: 256MiB
      oomScoreAdj: -1000
  duration: "30s"
