apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: reviews-fault-delay
spec:
  hosts:
  - reviews
  http:
  - fault:
      delay:
        percentage:
          value: 100
        fixedDelay: 15s
    route:
    - destination:
        host: reviews
        port:
          number: 9080
