apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: redis-cart-network-delay
spec:
  action: delay
  mode: one
  selector:
    labelSelectors:
      app: redis-cart
  delay:
    latency: "3s"
    correlation: "100"
    jitter: "50ms"
  duration: "60s"
