apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: productpage-fault-abort
spec:
  hosts:
  - productpage
  http:
  - fault:
      abort:
        percentage:
          value: 100
        httpStatus: 503
    route:
    - destination:
        host: productpage
        port:
          number: 9080
