apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kube-rca.agent.name" . }}-config
  labels:
    {{- include "kube-rca.agent.labels" . | nindent 4 }}
data:
  agent-config.yaml: |
    logLevel: {{ .Values.agent.logLevel | quote }}
    features:
      enableK8sCollector: true
