name: CI Helm

on:
  pull_request:
    paths: ['charts/**']

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: azure/setup-helm@v4
      - name: Add Bitnami chart repo
        run: helm repo add bitnami https://charts.bitnami.com/bitnami --force-update
      - name: Build chart dependencies
        run: helm dependency build charts/kube-rca
      - name: Lint kube-rca chart
        run: helm lint charts/kube-rca
